FORMAT: 1A
HOST: http://sqd.test.str8lines.com/simplyQuick/rest

# str8lines

The str8lines platform is a simple API allowing consumers to read and write data pertaining  product development processes.

# Str8Lines API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.



## Group ADMIN

Resources related to administrative functions in the API.


### Company 

A Company  has the following attributes:

+ uuid - the unique identifier of this item in the database
+ name - a unique name of this item in the database
+ 
### Office 
#### Get list of office countries [GET /office/countries]

+ Response 200 (application/json)

       {
            "data": {
                "countries": [
                    "South Korea",
                    "China",
                    "United States",
                    "Albania",
                    "Italy",
                    "India",
                    "Singapore",
                    "Taiwan"
                ]
            },
            "success": "true"
        }



### Business Roles


A Business Role has the following attributes:

+ uuid - the unique identifier of this item in the database
+ name - a unique name of this item in the database

#### Create Business Role [POST /domain/create]

+ Request (application/json)
    + Body
    
            {
                "type": "business_role",        // Mandatory
                "name": "New Role Name"         // Mandatory
            }

+ Response 200 (application/json)

        {
            "uuid": 21804,
            "name": "New Role Name"
        }

#### Get Business Roles for Context Company [GET /company/businessRole]


+ Response 200 (application/json)

        {
            "data": [
                {
                    "name": "Technical Design",
                    "uuid": "111.222.333",
                    "type": "business_role",
                },
                {
                    "name": "Design",
                    "uuid": "444.222.333",
                    "type": "business_role",
                }
            ],
            "success": "true"
        }

#### Get System Roles for Context Company [GET /company/role]


+ Response 200 (application/json)

        {
            "data": [
                {
                    "created": 1419251660755,
                    "description": "desc4",
                    "name": "sample_editor",
                    "uuid": "4",
                    "type": "s8_role_base",
                    "modified": 1419251660755
                },
                {
                    "created": 1419251660755,
                    "description": "desc3",
                    "name": "sample_editor",
                    "uuid": "3",
                    "type": "s8_role_base",
                    "modified": 1419251660755
                }
            ],
            "success": "true"
        }

## Update Business Role [POST /domain/update] 

+ Request (application/json)

    + Body
    
            {
                "business_role": {
                    "updated": [
                        {
                            "uuid": "111.222.333", 
                            "name": "New name",
                            "status": "active"
                        }
                    ]
                }
            }

+ Response 200 (application/json)


    + Body

            {
                "success": "true",
                "errors": [],       // will display 1 error for each item not updated
            }



## Time Periods [/season]

A Time object has the following attributes:

+ uuid - the unique identifier of this time period in the database

### View a Time Period [GET]


+ Response 200 (application/json)

        {
            "uuid": 21804,
            "name": "Fall 2014"
        }

## Silos [/silos]

A Silo object has the following attributes:

+ uuid - the unique identifier of this time period in the database
+ type (string) - The type of item to create
+ _access_token (string) - The Oauth2 access token used to validate access
+ _refresh_token (string) - The Oauth2 refresh token used to get a new access token
+ _description (string) - The description of the silo
+ _silo_type (string) - The type of the silo. (.e.g. ONEDRIVE_PERSONAL or ONEDRIVE_BUSINESS)
+ _end_point_uri (string) - The uri for the external service
+ _folder_list (string) - A comma seperated list of folder to be monitored
+ _last_processed_datetime (long)- The date and time in millisecond of when the folder was latest processed.


### Get all of the user's Silos [GET /silos]

+ Response 200 (application/json)

    + Body

            {
                "data":
                        [ 
                            {
                                "_access_token": "EwB4Aq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAQsixDYjwX8QDxj5AGZqZJR2DP5dhq19B9f7DW6KG234mtw/S7MhwZP7lgRrBKCr1FTHL51a98pq/AnBkj1uSggdnyfSqWVnruPSuVcauVOKEifa1yKxgYzZLDA0qhOyESPuGvH7Kga7EYgyrWykcjfeUh9RcH334+uuWp8EJ4a8GVkj8A6CPJvwX3ziqY15XH83DiHEXBCXLAyFrB+42OdOrfi5C++mqod9/X+h6XoSVUFpR9lxrgPim3hNvbwz4uW77xnup8v9Gwb13cABQmFXLf7FbBgKg7epRWGL9d8T4t9tvDbW76eroLZM60w2NrTxKt4p/4Hu6dTe+yypmYIDZgAACDT94VB+u1fWSAEqeJBYcONJfIQhDoCZLQouVGmnqVTn9sbbHxi5spHT9FozvL/obTAm9aEX0bxmvdhxeNZz4sQ7leddBXXl6Vg4F8PbEjej/ECwCpeoNqPN0gEo+4dCF5tESEGCkbO5n/gude0g/n/6f6TI0wve55ta5sw07d0nmancHClrExU54hoUCzHUMGkOC+uDeURNmQKEWQHz3zy2f4cVPLyO/nNvDZ0JDuLWuH4lZminhZdRz/SW/XvpsDwdstpOWSqa0AhNfqmoOp9KZiFpjZrRUIALWoSqF7zzrciNS3bzKndbVNvncVMU2rlqpSPHGrT6iQ76DPMA3aWonDrii8pzfZemCTjEHgujkbRZU1J/GY++T6Wgf7GTfzrcKmSGZqtcxHuHhbgdn9G4lDiTrxqg/MR9+cSyU/nFng6sv/JIXK0Fg4Sf9UMip8NMYgE=",
                                "_refresh_token": "MCmr3FhU0oHas!*kzSCNGid!nwVJKLflNrhaRZvuJS83RV5*s2qr6qYU2atoThqP40tY1zGu629jq3RZ3NN!ExZ40SI**6EtgVi48LKoELlPnEejP7Ez6g8dRhzeufkbd5rm1ocAVTB34NposKJUwd3VXFELnkuvSSP9A5vE66YrmJs9w*wJFPb5RU9JclGcD*Qk*qu5lU*0m*2s8aX2fltmS76H8s0RW1YLiMm2vt*Ig78llCnCa!aM3iKptuTOzfvzaLqy1kVuvY45Q6mHl2iA1RMrtO3BrFbDEMo7er7IzSZse6xtmF0PLhHsWy6DJtUu2d8S19DtbnKjBFxcl0mFf8Cha9PHwILpHuiOskz9gVezaqypVsWjYWoSwaRedTA$$",
                                "_silo_type": "ONEDRIVE_PERSONAL",
                                "_last_processed_datetime": "892342341124",
                                "_description": "This my OneDrive Personal folder",
                                "_end_point_uri": "",
                                "_folder_list": "1111111,232323",
                                "type": "s8_silo",
                                "uuid": "2924"
                            }
                        ],
                "success": "true"
            }

### Get user's Silo [GET /silos/{siloUUID}]

+ Parameters
    + siloUUID (long)

+ Response 200 (application/json)

    + Body

            {
                "data":
                    {
                        "_access_token": "EwB4Aq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAQsixDYjwX8QDxj5AGZqZJR2DP5dhq19B9f7DW6KG234mtw/S7MhwZP7lgRrBKCr1FTHL51a98pq/AnBkj1uSggdnyfSqWVnruPSuVcauVOKEifa1yKxgYzZLDA0qhOyESPuGvH7Kga7EYgyrWykcjfeUh9RcH334+uuWp8EJ4a8GVkj8A6CPJvwX3ziqY15XH83DiHEXBCXLAyFrB+42OdOrfi5C++mqod9/X+h6XoSVUFpR9lxrgPim3hNvbwz4uW77xnup8v9Gwb13cABQmFXLf7FbBgKg7epRWGL9d8T4t9tvDbW76eroLZM60w2NrTxKt4p/4Hu6dTe+yypmYIDZgAACDT94VB+u1fWSAEqeJBYcONJfIQhDoCZLQouVGmnqVTn9sbbHxi5spHT9FozvL/obTAm9aEX0bxmvdhxeNZz4sQ7leddBXXl6Vg4F8PbEjej/ECwCpeoNqPN0gEo+4dCF5tESEGCkbO5n/gude0g/n/6f6TI0wve55ta5sw07d0nmancHClrExU54hoUCzHUMGkOC+uDeURNmQKEWQHz3zy2f4cVPLyO/nNvDZ0JDuLWuH4lZminhZdRz/SW/XvpsDwdstpOWSqa0AhNfqmoOp9KZiFpjZrRUIALWoSqF7zzrciNS3bzKndbVNvncVMU2rlqpSPHGrT6iQ76DPMA3aWonDrii8pzfZemCTjEHgujkbRZU1J/GY++T6Wgf7GTfzrcKmSGZqtcxHuHhbgdn9G4lDiTrxqg/MR9+cSyU/nFng6sv/JIXK0Fg4Sf9UMip8NMYgE=",
                        "_refresh_token": "MCmr3FhU0oHas!*kzSCNGid!nwVJKLflNrhaRZvuJS83RV5*s2qr6qYU2atoThqP40tY1zGu629jq3RZ3NN!ExZ40SI**6EtgVi48LKoELlPnEejP7Ez6g8dRhzeufkbd5rm1ocAVTB34NposKJUwd3VXFELnkuvSSP9A5vE66YrmJs9w*wJFPb5RU9JclGcD*Qk*qu5lU*0m*2s8aX2fltmS76H8s0RW1YLiMm2vt*Ig78llCnCa!aM3iKptuTOzfvzaLqy1kVuvY45Q6mHl2iA1RMrtO3BrFbDEMo7er7IzSZse6xtmF0PLhHsWy6DJtUu2d8S19DtbnKjBFxcl0mFf8Cha9PHwILpHuiOskz9gVezaqypVsWjYWoSwaRedTA$$",
                        "_silo_type": "ONEDRIVE_PERSONAL",
                        "_last_processed_datetime": "892342341124",
                        "_description": "This my OneDrive Personal folder",
                        "_end_point_uri": "",
                        "_folder_list": "1111111,232323",
                        "type": "s8_silo",
                        "uuid": "2924"
                    },
                "success": "true"
            }

### Update user's Silo [PUT /silos/{siloUUID}]

+ Parameters
    + siloUUID (long)

+ Request (application/json)
    + Body
    
            {
                "_access_token": "EwB4Aq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAQsixDYjwX8QDxj5AGZqZJR2DP5dhq19B9f7DW6KG234mtw/S7MhwZP7lgRrBKCr1FTHL51a98pq/AnBkj1uSggdnyfSqWVnruPSuVcauVOKEifa1yKxgYzZLDA0qhOyESPuGvH7Kga7EYgyrWykcjfeUh9RcH334+uuWp8EJ4a8GVkj8A6CPJvwX3ziqY15XH83DiHEXBCXLAyFrB+42OdOrfi5C++mqod9/X+h6XoSVUFpR9lxrgPim3hNvbwz4uW77xnup8v9Gwb13cABQmFXLf7FbBgKg7epRWGL9d8T4t9tvDbW76eroLZM60w2NrTxKt4p/4Hu6dTe+yypmYIDZgAACDT94VB+u1fWSAEqeJBYcONJfIQhDoCZLQouVGmnqVTn9sbbHxi5spHT9FozvL/obTAm9aEX0bxmvdhxeNZz4sQ7leddBXXl6Vg4F8PbEjej/ECwCpeoNqPN0gEo+4dCF5tESEGCkbO5n/gude0g/n/6f6TI0wve55ta5sw07d0nmancHClrExU54hoUCzHUMGkOC+uDeURNmQKEWQHz3zy2f4cVPLyO/nNvDZ0JDuLWuH4lZminhZdRz/SW/XvpsDwdstpOWSqa0AhNfqmoOp9KZiFpjZrRUIALWoSqF7zzrciNS3bzKndbVNvncVMU2rlqpSPHGrT6iQ76DPMA3aWonDrii8pzfZemCTjEHgujkbRZU1J/GY++T6Wgf7GTfzrcKmSGZqtcxHuHhbgdn9G4lDiTrxqg/MR9+cSyU/nFng6sv/JIXK0Fg4Sf9UMip8NMYgE=",
                "_refresh_token": "MCmr3FhU0oHas!*kzSCNGid!nwVJKLflNrhaRZvuJS83RV5*s2qr6qYU2atoThqP40tY1zGu629jq3RZ3NN!ExZ40SI**6EtgVi48LKoELlPnEejP7Ez6g8dRhzeufkbd5rm1ocAVTB34NposKJUwd3VXFELnkuvSSP9A5vE66YrmJs9w*wJFPb5RU9JclGcD*Qk*qu5lU*0m*2s8aX2fltmS76H8s0RW1YLiMm2vt*Ig78llCnCa!aM3iKptuTOzfvzaLqy1kVuvY45Q6mHl2iA1RMrtO3BrFbDEMo7er7IzSZse6xtmF0PLhHsWy6DJtUu2d8S19DtbnKjBFxcl0mFf8Cha9PHwILpHuiOskz9gVezaqypVsWjYWoSwaRedTA$$",
                "_last_processed_datetime": "892342341124",
                "_description": "This my OneDrive Personal folder",
                "_folder_list": "1111111,232323"
            }
            
+ Response 200 (application/json)

    + Body

            {
                "data": [],
                "success": "true"
            }
            
### Delete user's Silo [DELETE /silos/{siloUUID}]
    
+ Response 200 (application/json)

    + Body

            {
                "data": [],
                "success": "true"
            }
            
## Group DOMAIN

Resources related to domain functions in the API.


### History 

A History object has the following attributes:

+ uuid - the unique identifier of this item in the database
+ timeStamp - the date/time the change was made
+ undo - whether or not hte change can be undone
+ log - the string of 'what was changed' to be presented to the user
+ timeDelta - the relative time as to when the change was made
+ userName - the full name of the user that made the change


#### Get history for a given record [GET /domain/history/get/{uuid}]


+ Response 200 (application/json)

        {
            data: [
                {
                    timeStamp: "Wed, 23 Sep 2015 14:33:08 GMT",
                    undo: false,
                    log: "app$history$created",
                    timeDelta: "9 hours ago",
                    userName: "Guy, Big",
                    uuid: "82518"
                }
            ],
            success: "true"        
        }



## Group USER

Resources related to user functions in the API.

## User [/user]

A User object has the following attributes:

+ uuid - the unique identifier of the user in the database
+ name - the unique name (email) of the user

### Get Users for Context Company [GET /users]

+ Response 200 (application/json)

    + Body

            {
                "data": [
                    {
                        "theme_mode": null,
                        "theme": null,
                        "companyAdmin": true,
                        "label": "admin@arribafashions.com",
                        "type": "s8_user",
                        "primaryImage": null,
                        "modified": 1428487382728,
                        "first_name": "",
                        "activation_link_window": null,
                        "mobile_phone": null,
                        "created": 1428487382728,
                        "name": "admin@arribafashions.com",
                        "s8_role_user": [
                            {
                                "created": 1428487382791,
                                "direction": "from",
                                "description": "Employee",
                                "name": "employee",
                                "uuid": "2316",
                                "type": "s8_role",
                                "relUUID": "4608",
                                "modified": 1428487382791
                            }
                        ],
                        "business_role_user": [
                            {
                                "name": "Technical Design",
                                "uuid": "2316",
                                "type": "business_role",
                            }
                        ],"last_name": "",
                        "active": true,
                        "uuid": "2308",
                        "s8_department_user": [
                            {
                                "created": 1428487382791,
                                "direction": "from",
                                "name": "Default Department",
                                "uuid": "2314",
                                "type": "s8_department",
                                "relUUID": "49500",
                                "modified": 1428487382791
                            },
                            {
                                "created": 1428487400724,
                                "direction": "from",
                                "name": "Big & Tall",
                                "active": true,
                                "uuid": "4717",
                                "type": "s8_department",
                                "relUUID": "49501",
                                "modified": 1428487400724
                            }
                        ],
                        "office_phone": null
                    }
                ]
            }      
            
### Add a Business Role/Role to a User [POST /addRole]

+ Request (application/json)

    + Body
    
            {
                "s8_user": {
                    "uuid": "111.222.333"    // mandatory - composite id
                },
                "s8_role": {                 // key can be s8_role or business_role
                    "uuid": "444.555.666"    // mandatory - composite id
                }
            }


+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }

### Add a Division to a User [POST /addDivision]

+ Request (application/json)

    + Body
    
            {
                "s8_user": {
                    "uuid": "111.222.333"    // mandatory - composite id
                },
                "s8_department": {
                    "uuid": "444.555.666"    // mandatory - composite id
                }
            }


+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }

### Remove a Division from a User [POST /removeDivision]

+ Request (application/json)

    + Body
    
            {
                "s8_user": {
                    "uuid": "111.222.333"    // mandatory - composite id
                },
                "s8_department": {
                    "uuid": "444.555.666"    // mandatory - composite id
                }
            }


+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }

### Get Context User's Divisions [GET /division]


+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }


## Group CLASSES

Resources related to classes

## Class [/class]

A Class object has the following attributes:

+ uuid - the unique identifier of this time period in the database
+ type (string) - The type of item to create
+ name (string) - The unique name of the class 
+ _classification_code (string) - The class code
+ _description - The description of the class

## Get All Classes [GET /classes] 


+ Response 200 (application/json)


    + Body

            {
            "data":[
                        {
                            "description":"Cashmere",
                            "name":"Cashmere",
                            "class_code":"",
                            "uuid":"5321",
                            "type":"s8_classification",
                            "s8_department_class":  [
                                {
                                    "name":"Activewear",
                                    "uuid":"5373",
                                    "type":"s8_department"
                                }
                            ]
                        }
                ],
                "success":"true"
            }
            

## Get Classes for a Department [GET /classes/{deptUUID}] 

+ Parameters
    + deptUUID (long)

+ Response 200 (application/json)


    + Body

            {
            "data":[
                        {
                            "description":"Cashmere",
                            "name":"Cashmere",
                            "class_code":"",
                            "uuid":"5321",
                            "type":"s8_classification",
                            "s8_department_class":  [
                                {
                                    "name":"Activewear",
                                    "uuid":"5373",
                                    "type":"s8_department"
                                }
                            ]
                        }
                ],
                "success":"true"
            }

## Add Class [POST /add] 


+ Request (application/json)

    + Body
    
            {
                "type": "s8_classification",
                "name": "Class1",
                "_classification_code": "CODE1",
                "_description": "description1"
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [
                            {
                                "description": "description1",
                                "name": "Class1",
                                "class_code": "CODE1",
                                "uuid": "5510",
                                "type": "s8_classification",
                                "s8_department_class": []
                            }
                        ],
                "success": "true"
            }
            
### Update Class [POST /update]

+ Request (application/json)

    + Body
    
            {
                "uuid": 5510
                "type": "s8_classification",
                "name": "Class1_Updated",
                "_classification_code": "CODE1",
                "_description": "description1"
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [
                            {
                                "description": "description1",
                                "name": "Class1",
                                "class_code": "CODE1",
                                "uuid": "5510",
                                "type": "s8_classification",
                                "s8_department_class": []
                            }
                        ],
                "success": "true"
            }
            
### Add Department to Class [POST /addDepartment]

+ Request (application/json)

    + Body
    
            {
                "type": "s8_classification",
                "uuid": "1500",
                "s8_department_classification": [
                    {
                        "type": "s8_department",
                        "uuid": "265"
                    }
                ]
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }

### Remove Department from Class [POST /removeDepartment]

+ Request (application/json)

    + Body
    
            {
                "type": "s8_classification",
                "uuid": "1500",
                "s8_department_classification": [
                    {
                        "type": "s8_department",
                        "uuid": "265"
                    }
                ]
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [],
                "success": "true"
            }


## Group FOLDERS

Resources related to folders

## Folder [/folder]

A Folder object has the following attributes:

+ uuid - the unique identifier of this time period in the database
+ type (string) - The type of folder
+ name (string) - The name of the folder
+ s8_parent_folder (string) - The parent folder
+ visible_to_folder - The visibility of the folder (brand, company, division, user)

## Create Folder [POST /domain/create] 


+ Response 200 (application/json)


    + Body

            {
                "name":"Sub Folder",
                "s8_folder_parent": "111.222.333",  //uuid of parent folder (optional)
                "type":"s8_folder",
                "visible_to_folder":  [ "5555.222.444"]  // array containing uuid(s) of access items (optional)
            }
          
## Delete folder [DELETE /folder/delete] 


+ Request  (application/json)


    + Body

            {
                
                "uuid": "111.222.333",  //uuid of folder 
            }
            
## Group PROJECT MANAGEMENT

Resources related to the project management capabilities

## Task [/proj]

A Task object has the following attributes:

+ uuid - the unique identifier of this object in the database (maps to uuid in db)
+ name - The name of the task
+ start_Date  - the start date of the task in the ISO 8601 format
+ end_date - the end date of the task in the ISO 8601 format
+ duration - the numeric part of the task duration (the number of units)
+ duration_unit - the unit part of the task duration, defaults to "d" (days). Valid values are:
    + "ms" (milliseconds)
    + "s" (seconds)
    + "mi" (minutes)
    + "h" (hours)
    + "d" (days)
    + "w" (weeks)
    + "mo" (months)
    + "q" (quarters)
    + "y" (years)
+ effort - the numeric part of the task effort (the number of units). The effort of the "parent" tasks will be automatically set to the sum of efforts of their "child" tasks
+ effort_unit - the unit part of the task effort, defaults to "h" (hours). Valid values are:
    + "ms" (milliseconds)
    + "s" (seconds)
    + "mi" (minutes)
    + "h" (hours)
    + "d" (days)
    + "w" (weeks)
    + "mo" (months)
    + "q" (quarters)
    + "y" (years)
+ pct_done - the current status of a task, expressed as the percentage completed (integer from 0 to 100)
+ css - A CSS class that will be applied to each rendered task DOM element
+ baseline_start_date - the baseline start date of the task in the ISO 8601 format.
+ baseline_end_date - the baseline end date of the task in the ISO 8601 format
+ baseline_pct_done - the baseline status of a task, expressed as the percentage completed (integer from 0 to 100)
+ calendar_id - the id of the calendar, assigned to task. Allows you to set the time when task can be performed. Should be only provided for specific tasks - all tasks by default are assigned to the project calen
+ scheduling_mode - the field, defining the scheduling mode for the task
+ manually_scheduled - When set to true, the StartDate of the task will not be changed by any of its incoming dependencies or constraints. Also, a manually scheduled parent task is not affected by its child tasks and behaves like any other normal task.
+ constraint_type - A string containing the alias for a constraint class (w/o the gntconstraint prefix). Valid values are:
    + "finishnoearlierthan"
    + "finishnolaterthan"
    + "mustfinishon"
    + "muststarton"
    + "startnoearlierthan"
    + "startnolaterthan"

## Get Projects [GET /proj/get] 


+ Response 200 (application/json)


    + Body

            {
    "data": [
        {
            "allow_dependencies": true,
            "created": "1445425909858",
            "pct_done": 0,
            "index": 0,
            "effort": 0,
            "scheduling_mode": "Normal",
            "leaf": false,
            "rgb": "{\"r\":0,\"g\":0,\"b\":255}",
            "type": "project",
            "duration_unit": "d",
            "uuid": "106804.2689.36531",
            "duration": 0,
            "expanded": true,
            "_primary_image": {},
            "children": [],
            "manually_scheduled": false,
            "baseline_pct_done": 0,
            "name": "p1",
            "modified": "1445425909858",
            "Id": "106804.2689.36531",
            "status": {
                "_primary_image": {},
                "name": "Active",
                "type": "s8_state",
                "uuid": "101401"
            }
        }
    ],
    "success": "true"
}
            
## Get Flat List of Projects [GET /proj/flatList] 


+ Response 200 (application/json)


    + Body

            {
                "data": [
                    {
                        "created": "1444747798298",
                        "pct_done": 0,
                        "index": 0,
                        "effort": 0,
                        "scheduling_mode": "Normal",
                        "leaf": false,
                        "type": "project",
                        "duration_unit": "d",
                        "uuid": "99986.2689.36531",
                        "duration": 0,
                        "expanded": true,
                        "_primary_image": {},
                        "children": [],
                        "manually_scheduled": false,
                        "baseline_pct_done": 0,
                        "name": "Project 100",
                        "modified": "1444776063313",
                        "Id": "99986.2689.36531",
                        "status": {
                            "_primary_image": {},
                            "name": "Inactive",
                            "type": "s8_state",
                            "uuid": "99933"
                        }
                    }
                ],
                "success": "true"
            }
                    
            
## Get Project/Project Template Details [GET /domain/details/get/{uuid}] 


+ Response 200 (application/json)


    + Body

            {
                "data": [
                    {
                        duration: 0,
                        created: "1443052329379",
                        manually_scheduled: false,
                        baseline_pct_done: 0,
                        name: "Project A",
                        description: "A project",
                        pct_done: 0,
                        modified: "1443052329379",
                        effort: 0,
                        type: "project",
                        uuid: "82265.2689.81131",
                        status: {
                            name: "active",
                            type: "s8_state",
                            uuid: "81232"
                        }
                    }
                ],
                "success":"true"
            }
            
## Get Project Templates [GET /template/get] 


+ Response 200 (application/json)


    + Body

            {
                data: [
                    {
                        duration: 0,
                        manually_scheduled: false,
                        name: "Project Template A",
                        s8_folder: {
                            name: "Soft Lines"
                            type: "s8_folder"
                            uuid: "87914.2689.4352"
                        },
                        history: [
                                {
                                    timeStamp: "Wed, 23 Sep 2015 14:33:08 GMT",
                                    undo: false,
                                    log: "Created",
                                    timeDelta: "4 hours ago",
                                    userName: "Guy, Big",
                                    uuid: "82518"
                                }
                        ],
                        messages: [
                            {
                                timeStamp: "Thu, 24 Sep 2015 17:24:32 GMT"
                                msg: "Message on project template"
                                timeDelta: "an hour ago"
                                userName: "Guy, Big"
                            },
                            {
                                timeStamp: "Thu, 24 Sep 2015 17:25:34 GMT"
                                msg: "Another message on project template"
                                timeDelta: "an hour ago"
                                userName: "Guy, Big"
                            },
                            {
                                timeStamp: "Thu, 24 Sep 2015 17:27:17 GMT"
                                msg: "Reply to a message"
                                timeDelta: "an hour ago"
                                userName: "Guy, Big"
                            }
                        ],
                        type: "project_template"
                        uuid: "87302.2689.81131"
                }
                ],
                "success":"true"
            }
            
## Get Dependencies, Assignments, Resources, and Tasks [GET /proj/get/{uuid}] 


+ Response 200 (application/json)


    + Body

            {
            "dependencies": {
                "rows" : [
                    {
                        "uuid"   : 1,
                        "From" : 11,
                        "To"   : 17
                    }
                ]
            },
             "assignments"  : {
                "rows" : [
                    {
                        "uuid"         : 1,
                        "TaskId"     : 11,
                        "ResourceId" : 1,
                        "units"      : 100
                    }
                ]
            },
            "resources" : {
                "rows" : [
                    {
                        "uuid"   : 1,
                        "Name" : "Mats"
                    }
                ]
            },
             "tasks" : {
                "rows" : [
                    {
                        "uuid"                : 1000,
                        "start_date"          : "2010-01-13",
                        "end_date"            : "2010-02-13",
                        "name"                : "Project A",
                        "type"                : "project",
                        "description"         : "Project A description",
                        "manually_scheduled"  : true,
                        "allow_dependencies"  : true,
                        "css"                 : "projectIcon",
                        "children"            : [
                            {
                                "baseline_end_date"   : "2010-02-01",
                                "uuid"                : 1,
                                "name"                : "Planning",
                                "pct_done"            : 50,
                                "start_date"          : "2010-01-18",
                                "baseline_start_date" : "2010-01-13",
                                "duration"            : 10,
                                "children"            : [ ]
                            }, {
                                "baseline_end_date"   : "2010-01-28",
                                "uuid"                : 11,
                                "name"                : "Investigate",
                                "pct_done"            : 50,
                                "task_type"           : "meeting",
                                "start_date"          : "2010-01-18",
                                "baseline_start_date" : "2010-01-20",
                                "segments"          : [ ]
                                "children"          : [ ]
                            }
                        ]
                    }
                ],
                "success":"true"
            }
            

## Get Flat List of Project Tasks [GET /proj/tasks/flatList?projects={projectUUID1},{projectUUID2},...] 


+ Response 200 (application/json)


    + Body

            {
                "data": {
                    "tasks": [
                        {
                            "name": "New Task",
                            "manually_scheduled": false,
                            "index": 0,
                            "start_date": "1444775786419",
                            "_primary_image": {},
                            "pct_done": 0,
                            "Id": "99995.2689.36694",
                            "leaf": false,
                            "duration": 1,
                            "created": "1444775973441",
                            "effort": 0,
                            "expanded": true,
                            "end_date": "1444775786419",
                            "modified": "1444776025566",
                            "baseline_pct_done": 0,
                            "children": [
                                {
                                    "name": "New Task2",
                                    "manually_scheduled": false,
                                    "index": 0,
                                    "start_date": "1444775786419",
                                    "_primary_image": {},
                                    "pct_done": 0,
                                    "Id": "100005.2689.36694",
                                    "leaf": false,
                                    "duration": 1,
                                    "created": "1444776025566",
                                    "effort": 0,
                                    "expanded": true,
                                    "end_date": "1444775786419",
                                    "modified": "1444776025566",
                                    "baseline_pct_done": 0,
                                    "children": [],
                                    "type": "task",
                                    "duration_unit": "d",
                                    "scheduling_mode": "Normal",
                                    "uuid": "100005.2689.36694"
                                }
                            ],
                            "type": "task",
                            "duration_unit": "d",
                            "scheduling_mode": "Normal",
                            "uuid": "99995.2689.36694"
                        },
                        {
                            "name": "New Task2",
                            "manually_scheduled": false,
                            "index": 0,
                            "start_date": "1444775786419",
                            "_primary_image": {},
                            "pct_done": 0,
                            "Id": "100005.2689.36694",
                            "leaf": false,
                            "duration": 1,
                            "created": "1444776025566",
                            "effort": 0,
                            "expanded": true,
                            "end_date": "1444775786419",
                            "modified": "1444776025566",
                            "baseline_pct_done": 0,
                            "children": [],
                            "type": "task",
                            "duration_unit": "d",
                            "scheduling_mode": "Normal",
                            "uuid": "100005.2689.36694"
                        },
                        {
                            "name": "New Task3",
                            "manually_scheduled": false,
                            "index": 0,
                            "start_date": "1444775786419",
                            "_primary_image": {},
                            "pct_done": 0,
                            "Id": "100015.2689.36694",
                            "leaf": false,
                            "duration": 2,
                            "created": "1444776063171",
                            "effort": 0,
                            "expanded": true,
                            "end_date": "1444775786419",
                            "modified": "1444776063171",
                            "baseline_pct_done": 0,
                            "children": [],
                            "type": "task",
                            "duration_unit": "d",
                            "scheduling_mode": "Normal",
                            "uuid": "100015.2689.36694"
                        }
                    ],
                    "projects": [
                        {
                            "name": "Project 100",
                            "manually_scheduled": false,
                            "index": 0,
                            "_primary_image": {},
                            "pct_done": 0,
                            "Id": "99986.2689.36531",
                            "leaf": false,
                            "duration": 0,
                            "created": "1444747798298",
                            "effort": 0,
                            "expanded": true,
                            "modified": "1444776063313",
                            "baseline_pct_done": 0,
                            "children": [],
                            "type": "project",
                            "duration_unit": "d",
                            "scheduling_mode": "Normal",
                            "uuid": "99986.2689.36531"
                        }
                    ]
                },
                "success": "true"
            }


## Update Schedule [POST /proj/update] 

+ Request (application/json)

    + Body
    
            {
                "uuid": "1500",
                "project_id": 1010    /// mandatory
                "resources": {
                    "added": [
                        {
                            "uuid": 101           // mandatory - must be uuid of person or role
                        }
                    ],
                    "deleted": [
                        {
                            "uuid": 101           // mandatory - must be uuid of person or role
                        }
                    ]
                },
                "tasks": {
                    "updated": [
                        {
                            "uuid": 50, 
                            "start_date": "2010-02-18T00:00:00-05:00",
                            "end_date": "2010-02-18T00:00:00-05:00",
                            "duration": 273,
                            "pct_done": 50.33,
                            "name:" "Investigation",
                            "folder_content": "111.222.333"        // optional - composite uuid of folder to move to 
                        }
                    ],
                    "added": [
                        {
                            "start_date": "2015-08-19T00:00:00-04:00",
                            "end_date": "2015-08-20T00:00:00-04:00",
                            "duration": 1,
                            "duration_unit": "d",
                            "name": "New Task",
                            "ParentId:" 50                          //mandatory
                            "PhantomId": "phantomCreatedByBryntum"  //mandatory
                        }
                    ],
                    "deleted": [
                        {
                            "uuid": 1234                        //mandatory
                        }
                    ]
                },
                "dependencies": {
                    "added": [
                        {
                            "PhantomId": "phantomCreatedByBryntum" // mandatory
                            "From": 101,                           // mandatory - can use Phantom String for Task
                            "To": 102,                             // mandatory - can use Phantom String for Task
                            "lag": 0,
                            "lag_unit": "d"
                        }
                    ],
                    "updated": [
                        {
                            "uuid": 123,                            // mandatory
                            "From": 102,
                            "To": 103,
                            "lag": 1,
                            "lag_unit": "m"
                        }
                    ],
                    "deleted": [
                        {
                            "uuid": 124
                        }
                    ]
                },
                ,
                "assignments": {
                    "added": [
                        {
                            "PhantomId": "phantomCreatedByBryntum" // mandatory
                            "TaskId": 101,                         // mandatory - can use Phantom String for Task
                            "ResourceId": 102,                     // mandatory - must be valid user uuid
                            "units": 0,
                        }
                    ],
                    "updated": [
                        {
                            "uuid": 123,                            // mandatory
                            "units": 50,
                        }
                    ],
                    "deleted": [
                        {
                            "uuid": 124
                        }
                    ]
                }
            }

+ Response 200 (application/json)


    + Body

            {
                "success": "true",
                "errors": [],       // will display 1 error for each task not updated
                "tasks": []         // will contain added tasks with uuids (updates/deletes will not be included)
            }

## Add Project [POST /domain/create?foo=1] 

+ Request (application/json)

    + Body
    
            {
                "name": "New Project",
                "roles": [ 101, 102, 103 ],
                "resources": [ 201, 202, 203 ],
                "visible_to": [ 401 ],
                "color": "#490390",
                "image": { std primary image },
                "type": "project"
               
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [ 
                    {
                        "uuid": 500
                    }
                ],
                "success": "true"
            }
            
## Add Project Template [POST /domain/create] 

+ Request (application/json)

    + Body
    
            {
                "name": "t1",
                "description": "d1",
                "status": "",
                "id": "Str8lines_desktop.model.DynamicGridModelext-332-2",
                "type": "project_template",
                "folder_content": "82225.2689.4352"
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [
                    {
                        "allow_dependencies": true,
                        "s8_folder": {
                            "_primary_image": {},
                            "children": [],
                            "uuid": "82225.2689.4352"
                        },
                        "created": "1445704008987",
                        "pct_done": 0,
                        "index": 0,
                        "description": "d1",
                        "effort": 0,
                        "history": [
                            {
                                "timeStamp": "Oct 24, 2015 6:26 PM",
                                "image": {
                                    "_file_url": {}
                                },
                                "undo": false,
                                "log": "Created ",
                                "timeDelta": "a few mins ago",
                                "userName": ", ",
                                "uuid": "109220"
                            }
                        ],
                        "scheduling_mode": "Normal",
                        "leaf": false,
                        "type": "project_template",
                        "duration_unit": "d",
                        "uuid": "109213.2689.81131",
                        "duration": 0,
                        "expanded": true,
                        "_primary_image": {},
                        "children": [],
                        "manually_scheduled": false,
                        "baseline_pct_done": 0,
                        "name": "t1",
                        "modified": "1445704008987",
                        "Id": "109213.2689.81131",
                        "status": {
                            "_primary_image": {},
                            "type": "s8_state",
                            "uuid": "81232"
                        }
                    }
                ],
                "success": "true"
            }

## Scheduled Meeting [/meeting]

A Scheduled Meeting object has the following attributes:

+ uuid
+ type
+ organizer (IUserDO)- user who created meeting
+ attendee (IUserDO) - users that attend meeting
+ subject (String) - Subject of meeting
+ description (String) - Description of meeting
+ location (String) - Location where meeting will take place
+ start_date (Long) - Start date of meeting in milliseconds
+ end_date (Long) - End date of meeting in milliseconds

## Create Scheduled Meeting [POST /meeting/create] 

+ Request (application/json)

    + Body

            {
                "organizer": "2690.2689.2690",
                "attendees": [
                    "13877.2689.13877",
                    "14111.2689.14111"
                ],
                "description": "testing meeting stuff . This is description",
                "start_date": "1359760320000",
                "end_date": "1359720720000",
                "location": "conference room",
                "subject": "Test meetings",
                "type": "scheduled_meeting"
            }
        
+ Response 200 (application/json)


    + Body

            {
                "data": [{
                    "end_date": "1359720720000",
                    "subject": "Test meetings",
                    "attendees": [{
                        "office_phone": "",
                        "theme_mode": "",
                        "mobile_phone": "",
                        "last_name": "Vava",
                        "active": false,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "13877.2689.13877",
                        "first_name": "Fotini",
                        "companyAdmin": false,
                        "email": "fotini.vava@str8lines.com"
                    }, {
                        "office_phone": "",
                        "theme_mode": "",
                        "mobile_phone": "",
                        "last_name": "Lewis",
                        "active": true,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "14111.2689.14111",
                        "first_name": "Darcy",
                        "companyAdmin": false,
                        "email": "darcy.lewis@str8lines.com"
                    }],
                    "created": "1446116055773",
                    "description": "testing meeting stuff . This is description",
                    "type": "scheduled_meeting",
                    "uuid": "114467.2689.114369",
                    "_primary_image": {},
                    "organizer": {
                        "office_phone": "(+1) 253 219 2569",
                        "theme_mode": "",
                        "mobile_phone": "(+1) 253 219 2569",
                        "last_name": "Guy",
                        "active": true,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "2690.2689.2690",
                        "first_name": "Big",
                        "companyAdmin": true,
                        "email": "admin.arriba@str8lines.com"
                    },
                    "name": "114467",
                    "modified": "1446116055773",
                    "location": "conference room",
                    "start_date": "1359760320000",
                    "status": {
                        "_primary_image": {},
                        "created": "1446115870414",
                        "name": "init",
                        "modified": "1446115870414",
                        "type": "s8_state",
                        "uuid": "114397"
                    }
                }],
                "success": "true"
            }
            
## Read Scheduled Meeting  [GET /meeting/get]

+ Response 200 (application/json)

    + Body

            {
                "data": [{
                    "end_date": "1420200720000",
                    "subject": "Test meetings",
                    "attendees": [],
                    "created": "1446114051027",
                    "description": "testing meeting stuff . This is description",
                    "type": "scheduled_meeting",
                    "uuid": "114467.2689.114369",
                    "_primary_image": {},
                    "organizer": {
                        "office_phone": "(+1) 253 219 2569",
                        "theme_mode": "",
                        "mobile_phone": "(+1) 253 219 2569",
                        "last_name": "Guy",
                        "active": true,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "2690.2689.2690",
                        "first_name": "Big",
                        "companyAdmin": true,
                        "email": "admin.arriba@str8lines.com"
                    },
                    "name": "114467",
                    "modified": "1446114198732",
                    "location": "conference room",
                    "start_date": "1420114320000",
                    "status": {
                        "_primary_image": {},
                        "name": "init",
                        "type": "s8_state",
                        "uuid": "114397"
                    }
                }],
                "success": "true"
            }
            
## Edit Scheduled Meeting [POST /meeting/update/{meetingUUID}] 

+ Parameters
    + meetingUUID (long)
+ Request


    + Body

            {
                "start_date": "1420114320000",
                "end_date": "1420200720000"
            }

+ Response 200 (application/json)


    + Body

            {
                "data": [{
                    "end_date": "1420200720000",
                    "subject": "Test meetings",
                    "attendees": [{
                        "office_phone": "",
                        "theme_mode": "",
                        "mobile_phone": "",
                        "last_name": "",
                        "active": false,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "14111.2689.14111",
                        "first_name": "",
                        "companyAdmin": false,
                        "email": "darcy.lewis@str8lines.com"
                    }, {
                        "office_phone": "",
                        "theme_mode": "",
                        "mobile_phone": "",
                        "last_name": "",
                        "active": false,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "13877.2689.13877",
                        "first_name": "",
                        "companyAdmin": false,
                        "email": "fotini.vava@str8lines.com"
                    }],
                    "created": "1446116055773",
                    "description": "testing meeting stuff . This is description",
                    "type": "scheduled_meeting",
                    "uuid": "114467.2689.114369",
                    "_primary_image": {},
                    "organizer": {
                        "office_phone": "",
                        "theme_mode": "",
                        "mobile_phone": "",
                        "last_name": "",
                        "active": false,
                        "theme": "",
                        "type": "s8_user",
                        "uuid": "2690.2689.2690",
                        "first_name": "",
                        "companyAdmin": false,
                        "email": "admin.arriba@str8lines.com"
                    },
                    "name": "114467",
                    "modified": "1446116055773",
                    "location": "conference room",
                    "start_date": "1420114320000",
                    "status": {
                        "_primary_image": {},
                        "name": "init",
                        "type": "s8_state",
                        "uuid": "114397"
                    }
                }],
                "success": "true"
            }
    
            
## Group USER INTERFACE

Resources related to user interface

### UI [/ui]

A UI object has the following attributes:

+ to be filled in...

### Get Template UI [GET /ui/template]

+ Response 200 (application/json)

    + Body
    
            {
                data:
                {
                    tree:
                    [
                        {
                        _c: "node_folder"
                        children: 
                        [
                            {
                                _c: "node_folder"
                                _t: "s8_folder"
                                _v: "62106"
                                _f: "s8_folder"
                                count: 0
                                _l: "Home"
                            },
                            {
                                _c: "node_folder"
                                _t: "s8_folder"
                                _v: "62103"
                                _f: "s8_folder"
                                count: 0
                                _l: "Apparel"
                            }
                        _t: "s8_folder"
                        _v: "62100"
                        _f: "s8_folder"
                        count: 0
                        _l: "Soft Lines"
                        }
                    ],
                    fields: 
                    [
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: false
                            label: "actions"
                            type: "action"
                            actions: 
                            [
                                {
                                    _c: "open"
                                    _css: "open"
                                    _l: "Open"
                                },
                                {
                                    _c: "delete"
                                    _css: "delete"
                                    _l: "Delete"
                                }
                        },
                        {
                            system: true
                            freezePane: false
                            hidden: false
                            editable: false
                            type: "text_filed"
                            key: "uuid"
                        },
                        {
                            system: true
                            freezePane: false
                            hidden: false
                            editable: false
                            type: "text_filed"
                            key: "s8_folder"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Code"
                            type: "text_filed"
                            key: "name"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Description"
                            type: "text_filed"
                            key: "description"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Date Created"
                            type: "date"
                            key: "created"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Date Last Used"
                            type: "date"
                            key: "last_used"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Status"
                            type: "select"
                            choices: 
                            [
                                {
                                    display: "active 4529"
                                    name: "active"
                                    UUID: "4529"
                                    value: "4529"
                                },
                                {
                                    display: "inactive 33092"
                                    name: "inactive"
                                    UUID: "33092"
                                    value: "33092"
                                }
                            ],
                            key: "status"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Recent Messages"
                            type: "message"
                            key: "messages"
                        },
                        {
                            system: false
                            freezePane: false
                            hidden: false
                            editable: true
                            label: "Recent Changes"
                            type: "history"
                            key: "history"
                        },
                        chart: {
                            key: "status"
                        },
                    }
                    
                success: "true"
            }
            
## Group EXTERNAL STORAGE

Resources related to 3rd party cloud base storage solutions (e.g. OneDrive, Google Drive, Box)

### Group Authentication

Each third party solution will have a different URIs to called. However, all the third party solutions provide Oauth2 authentication. Oauth2 provides an access token and a refresh token. The access token is used to determine access to the user's information. The access token generally expires in one hour. The refresh token is used to get a new access token. It generally expires after 90 days. The 'http://&lt;server&gt;/&lt;webapp&gt;/auth/onedrive' servlet stores the access token and the refresh token in a user's silo so that it can reference at a later time. The client will finally be redirect to 'http://&lt;server&gt;/&lt;webapp&gt;/siloDialog.jsp?siloUUID=&lt;siloUUID&gt;'.


#### OneDrive for Personal

+ Oauth2 URI - https://login.live.com/oauth20_authorize.srf

+ Parameters:
    + client_id - The id of the client registered at 'https://account.live.com/developers/applications/index'. This the StraightLines registered app.For our purposes the value is '000000004016787D'
    + scope - Determines what type of access the app is granted when the app is signed in. For our purposes the value is wl.signin and wl.offline_access. The value should be URL encoded.
    + response_type - Oauth2 allows for 2 types of responses token and code. For our purposes the value is 'code'.
    + redirect_uri - Once a token is generated, it is passed back to the redirect_uri. This uri must match the uri set in StrightLines regestered app. The value should be URL encoded.
    + state - Oauth2 allows for data to pass from the client to redirect_uri using this parameter. For our purposes the value is the user UUID and company UUID piped seperated.

+ Example - https://login.live.com/oauth20_authorize.srf?client_id=000000004016787D&scope=wl.signin%20wl.offline_access&response_type=code&redirect_uri=http%3A%2F%2Fbrentrudd.ddns.net%2FsimplyQuick%2Fauth%2Fonedrive&state=2678|0

+ Reference - https://dev.onedrive.com/auth/msa_oauth.htm

#### OneDrive for Business

+ Oauth2 URI - https://login.windows.net/common/oauth2/authorize

+ Parameters:
    + client_id - The id of the client registered at 'https://manage.windowsazure.com/str8lines.com#Workspaces/All/dashboard'. This the StraightLines registered app.For our purposes the value is '000000004016787D'
    + response_type - Oauth2 allows for 2 types of responses token and code. For our purposes the value is 'code'.
    + redirect_uri - Once a token is generated, it is passed back to the redirect_uri. This uri must match the uri set in StrightLines regestered app. The value should be URL encoded.
    + state - Oauth2 allows for data to pass from the client to redirect_uri using this parameter. For our purposes the value is the user UUID and company UUID piped seperated.

+ Example - https://login.windows.net/common/oauth2/authorize?client_id=753abfd8-d355-443c-90d7-27215bf073f6&response_type=code&redirect_uri=http%3A%2F%2Fbrentrudd.ddns.net%2FsimplyQuick%2Fauth%2Fonedrivebusiness&state=2678|0

+ Reference - https://dev.onedrive.com/app-registration.htm#register-your-app-for-onedrive-for-business

### Group External Service API

#### List Root Contents [GET /silos/list/{soliUUID}]

List items of root directory

+ Parameters
    + soliUUID (long)

+ Response 200 (application/json)


    + Body
    
            {
                "data": [
                    {
                        "size": 1493,
                        "name": "Documents",
                        "create": 1380726528523,
                        "modified": 1380726591021,
                        "id": "7FED01C5C174810!106"
                    },
                    {
                        "size": 10399,
                        "name": "folder1",
                        "create": 1440085770013,
                        "modified": 1441139873367,
                        "id": "7FED01C5C174810!109"
                    },
                    {
                        "size": 20725,
                        "name": "Color0.gif",
                        "create": 1440085792085,
                        "modified": 1440089683033,
                        "id": "7FED01C5C174810!110",
                        "uri": "https://public-dm2306.files.1drv.com/y3mAJ0FdODCosvI8JRD1FNutz7KzXfNLfFUukhrZHOX-153DJFklRe-j_kPX9CYAmJajrVEdbwneyvEzSgpXDolRZeNlZCdQ4ibEWXVXCeiUwux2mmFobx-DBdYUUdlNP3Fk0t9RmwJoIuukVdXBK8Ky2aHK8ATWVEqjqMSrftwPhS8QBgWTbl6anNON5oXyIL8gv64RFpWIpeeRk0wQQ0hww"
                    }
                ],
                "success": "true"
            }

#### List Directory Contents [GET /silos/list/{soliUUID}/{directoryId}]

List items in directory

+ Parameters
    + soliUUID (long)
    + directory (string) - This should be URL encoded

+ Response 200 (application/json)


    + Body
    
            {
                "data": [
                    {
                        "size": 1493,
                        "name": "Documents",
                        "create": 1380726528523,
                        "modified": 1380726591021,
                        "id": "7FED01C5C174810!106"
                    },
                    {
                        "size": 10399,
                        "name": "folder1",
                        "create": 1440085770013,
                        "modified": 1441139873367,
                        "id": "7FED01C5C174810!109"
                    },
                    {
                        "size": 20725,
                        "name": "Color0.gif",
                        "create": 1440085792085,
                        "modified": 1440089683033,
                        "id": "7FED01C5C174810!110",
                        "uri": "https://public-dm2306.files.1drv.com/y3mAJ0FdODCosvI8JRD1FNutz7KzXfNLfFUukhrZHOX-153DJFklRe-j_kPX9CYAmJajrVEdbwneyvEzSgpXDolRZeNlZCdQ4ibEWXVXCeiUwux2mmFobx-DBdYUUdlNP3Fk0t9RmwJoIuukVdXBK8Ky2aHK8ATWVEqjqMSrftwPhS8QBgWTbl6anNON5oXyIL8gv64RFpWIpeeRk0wQQ0hww"
                    }
                ],
                "success": "true"
            }

